from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_cv():
    # Crea un documento PDF
    c = canvas.Canvas("cv.pdf", pagesize=letter)

    # Agrega contenido al currículum
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 750, "Currículum Vitae")
    c.setFont("Helvetica", 12)
    c.drawString(50, 700, "Nombre: Bruno Ruiz Talamo")
    c.drawString(50, 680, "Descripción:")
    c.setFont("Helvetica", 10)
    c.drawString(50, 660, "Nacido el 13 de Junio de 1992.")
    c.drawString(50, 640, "Proactivo, respetuoso, ayudante, educado.")
    c.drawString(50, 620, "Nivel de inglés avanzado.")
    c.drawString(50, 600, "Tercer año de Comercio Internacional - CAECE")
    c.drawString(50, 580, "Responsive Web Design")
    c.drawString(50, 560, "Desarrollador Python Jr - Entry Level")
    c.drawString(50, 540, "+54 223 582 7967")
    c.drawString(50, 520, "Mail: brunoruiztalamo@icloud.com")
    c.drawString(50, 500, "Mar del Plata, Buenos Aires, Argentina")
    c.drawString(50, 480, "LinkedIn: /in/brunoruiztalamo")
    c.drawString(50, 460, "GitHub: /brunoruiztalamo/portfolio")
    c.drawString(50, 440, "Experiencia Personal:")
    c.setFont("Helvetica", 10)
    c.drawString(50, 420, "- MALCRIADA RESTAURANT - ADICIONISTA")
    c.drawString(50, 400, "  Actividades: Adición, control de sistema FUDO, control de flujo de dinero, stock, proveedores.")
    c.drawString(50, 380, "- RAMONA RESTAURANT & BAR - ENCARGADO")
    c.drawString(50, 360, "  Actividades: Control de personal, control del establecimiento, control de flujo de dinero, control de stock.")
    c.drawString(50, 340, "- ESTUDIO AMEZTOY – BEST LOG SRL | Operador de CI / Logística")
    c.drawString(50, 320, "  Actividades: Gestión operativa de comercio internacional - confección de documentación de transporte.")
    c.drawString(50, 300, "  Confección de documentación legal. Confección de documentación de carácter internacional.")
    c.drawString(50, 280, "- ESTUDIO ADUANERO TALAMO SRL | Traductor de Comercio Internacional")
    c.drawString(50, 260, "  Actividades: Traductorado y confección de documentación y textos - Contacto con empresas")
    c.drawString(50, 240, "Idiomas:")
    c.setFont("Helvetica", 10)
    c.drawString(50, 220, "- Español Nativo. (Estudios Primarios y Secundarios Completados).")
    c.drawString(50, 200, "- Inglés: Nivel Avanzado. Inglés Técnico en Comercio Internacional.")
    c.drawString(50, 180, "  Egresado del Instituto Cultural Americano (ICA) en Mar del Plata.")
    c.drawString(50, 160, "  Exámenes hechos: PET, First Certificate, ECCE. / Calif. C2 Proficient en EF.")
    c.drawString(50, 140, "  Standard English Test. Marzo 2022.")
    c.drawString(50, 120, "Estudios:")
    c.setFont("Helvetica", 10)
    c.drawString(50, 100, "- UNIVERSIDAD CAECE – MAR DEL PLATA")
    c.drawString(50, 80, "  Estado: Transitando el 3er y 4to año de estudio. Por problemas económicos, tuve que dejar la carrera por tiempo indeterminado.")
    c.drawString(50, 60, "- INSTITUTO CULTURAL AMERICANO – MAR DEL PLATA (ICA)")
    c.drawString(50, 40, "  Estado: Inglés avanzado. Completé los exámenes First Certificate y ECCE (Michigan).")
    c.drawString(50, 20, "  Completé el examen ‘EF’ de nivelación de inglés internacional con nivel C2.")
    c.drawString(50, 0, "- GOOGLE POR ARGENTINA – MAR DEL PLATA (SHERATON HOTEL)")
    c.drawString(50, -20, "  Estado: Curso completado. Diploma otorgado por Google en reconocimiento de mis conocimientos adquiridos sobre las apps de Google Business (Ads, Meet, Duo, Website, etc).")
    c.drawString(50, -40, "- RESPONSIVE WEB DESIGN CERTIFICATION")
    c.drawString(50, -60, "  Estado: Certificado de +300 hs de estudio con HTML+CSS3")
    c.drawString(50, -80, "- JAVASCRIPT ALGORITHM AND DATA STRUCTURES CERTIFICATION")
    c.drawString(50, -100, "  Estado: Certificado de +300 hs de estudio con JavaScript")
    c.drawString(50, -120, "- DESARROLLADOR PYTHON")
    c.drawString(50, -140, "  Estado: Estudiante en la comisión 55350. Certificado otorgado por Coderhouse.com.")

    # Finaliza y guarda el documento PDF
    c.save()

# Llama a la función para crear el currículum
create_cv()